import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || '';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || '';

// Note: To use Supabase, you must add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY 
// to your environment variables in AI Studio.
export const supabase = createClient(supabaseUrl, supabaseAnonKey);

/**
 * Step-by-step guide to connect Supabase:
 * 
 * 1. Create a project in https://supabase.com
 * 2. Go to Project Settings > API to get your URL and Anon Key.
 * 3. Add them to AI Studio Secrets as VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY.
 * 4. Run the following SQL in the Supabase SQL Editor to create the tables:
 * 
 * CREATE TABLE EXPEDIENTES (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   numero_expediente TEXT UNIQUE,
 *   denunciante_nombre TEXT,
 *   denunciante_dni TEXT,
 *   denunciante_email TEXT,
 *   denunciante_telefono TEXT,
 *   denunciante_calle TEXT,
 *   denunciante_numeracion TEXT,
 *   denunciante_barrio TEXT,
 *   denunciante_entre_calle_1 TEXT,
 *   denunciante_entre_calle_2 TEXT,
 *   denunciante_lote TEXT,
 *   empresa_denunciada TEXT,
 *   empresa_denunciada_2 TEXT,
 *   empresa_denunciada_3 TEXT,
 *   empresa_denunciada_4 TEXT,
 *   motivo_reclamo TEXT,
 *   peticiones TEXT,
 *   estado TEXT DEFAULT 'Ingresado',
 *   fecha_ingreso TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
 *   fecha_resolucion TIMESTAMP WITH TIME ZONE,
 *   fecha_cambio_estado TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
 *   tramite TEXT,
 *   observaciones TEXT,
 *   prueba_documental_1 TEXT,
 *   prueba_documental_2 TEXT
 * );
 * 
 * CREATE TABLE AUDIENCIAS (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   expediente_id BIGINT REFERENCES EXPEDIENTES(id),
 *   fecha_hora TIMESTAMP WITH TIME ZONE,
 *   tipo TEXT,
 *   estado TEXT DEFAULT 'Programada'
 * );
 * 
 * CREATE TABLE MOVIMIENTOS (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   expediente_id BIGINT REFERENCES EXPEDIENTES(id),
 *   fecha TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
 *   accion TEXT,
 *   usuario TEXT,
 *   observacion TEXT
 * );
 * 
 * CREATE TABLE USUARIOS (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   nombre TEXT UNIQUE,
 *   email TEXT UNIQUE,
 *   password TEXT,
 *   rol TEXT DEFAULT 'admin'
 * );
 * 
 * CREATE TABLE CONFIGURACION (
 *   key TEXT PRIMARY KEY,
 *   value TEXT
 * );
 * 
 * INSERT INTO CONFIGURACION (key, value) VALUES ('next_expediente_number', '1');
 */
